# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  default:
    deps:
      - dev
      - pb
  dev: 
    cmds:
      - npm run dev
  pb:
    dir: pocketbase
    cmd: ./pocketbase.exe serve
    
