# https://taskfile.dev

version: '3'

dotenv: [.env]

tasks:
  default:
    deps:
      - dev
      - pb
  dev: 
    cmds:
      - npm run dev
  pb:
    dir: pocketbase
    cmd: ./pocketbase.exe serve
  types:
    cmd: npx pocketbase-typegen --db ./pocketbase/pb_data/data.db --out ./src/lib/pocketbase-types.ts
    aliases:
      - type
      - t
  install:
    cmds:
      - npm i
      - touch .env
  example:
    aliases:
      - seed
      - testdata
    cmd: node pocketbase/seed-en.mjs
    
